### ISSUE TITLE
Wrong coverage report?

### ISSUE THREAD

**Issue by akhilsbehl** [pytest-dev/pytest-cov#118]
![screenshot from 2016-05-18 18-15-06](https://cloud.githubusercontent.com/assets/1821778/15358918/7e455446-1d24-11e6-8e88-94f74c96925b.png)

Umm... how is it that that statement could be uncovered given that the one above is covered? I'm doing coverage testing for the first time. So any explanation is helpful.

Thanks.

**Comment by The-Compiler** [comment]
You should probably report this to https://bitbucket.org/ned/coveragepy/ as this is just the plugin integrating coverage with pytest. Mentioning @nedbat here so he can chime in though :wink:

The only way I can see this happening is by the `cls(...)` call raising an exception.

What happens if you do `raise Exception("Hello World")` instead of `return instance` - is that actually reached, i.e. is that exception triggered?

**Comment by ionelmc** [comment]
Ha, @The-Compiler beat me to it!

@akhilsbehl posting an working example usually helps a lot.

**Comment by akhilsbehl** [comment]
You guys are right! I figured this while I was writing the issue and then decided to first check my hypothesis. Essentially, all tests through that function were testing Exceptions. So it never really returned successfully.

Closing this as a false alarm.

Thanks for help.
