### ISSUE TITLE
html report does not work on many test files

### ISSUE THREAD

**Issue by markfink** [pytest-dev/pytest-cov#138]
I am a big fan of *--cov-report*. So today I started using the html format. Strange things happen... It took me a while to realize:

this works (**finds two test files**):
```bash
python -m pytest -vv --cov-report html --cov=beedo tests/test_h*.py
```
the htmlcov folder is created and contains nice reports...

this does not work (**finds 7 test files**):
```bash
python -m pytest -vv --cov-report html --cov=beedo tests/test_*.py
```
it says "Coverage HTML written to dir htmlcov" like before but no folder and no reports :(

BTW the following works fine, too:
```bash
python -m pytest -vv --cov-report term-missing --cov=beedo tests/test_*.py
```
and I get a nice text report. So I am pretty sure my tests do not cause this issue but the html output.
**Any idea how to amp up the logging to get more info on this?**

**Comment by ionelmc** [comment]
How many test files? Also, do you do anything strange in your tests? Check
if there's a test that triggers the issue.

**Comment by markfink** [comment]
How many test files? **7**
Check if there's a test that triggers the issue. => **Any idea how to amp up the logging to get more info on this?**
BTW, I don't think I ever wrote a strange test but I am not a pytest-cov expert so what does strange in this context mean?

**Comment by ionelmc** [comment]
You could identify the test (if it's caused by one of the tests disabling the coverage tracer, or use of a profiler, `sys.settrace` etc) by using xdist's "boxed mode": add `--boxed` cmd line and check which tests don't have any coverage (you need to enable reporting/coverage on the tests).

If that don't clear it up then it could be a pytest-cov bug I guess, but I'd need to see some example that reproduces the issue.

**Comment by markfink** [comment]
the --boxed option solves the problem
