### ISSUE TITLE
Incomplete coverage when run via setup.py

### ISSUE THREAD

**Issue by teake** [pytest-dev/pytest-cov#147]
Running test via `python setup.py` yields incomplete coverage for me, whereas running it directy via pytest gives the correct coverage. 
I'm at Python 3.5.1 and pytest 3.0.5. I've tried both the pytest-cov 2.4.0 release and the latest master (609c1be), to no avail. Here are the steps to reproduce the problem:

1. Load Python 3.5.x (v)env
2. `$ git clone https://gitlab.astro-wise.org/omegacen/vcsinfo.git`
3. `$ cd vcsinfo`
4. `$ git checkout a015054e461101290726cdf6a3e67100bbfa1f36`
5. `$ python setup.py test`

The coverage report then reads:

```
----------- coverage: platform linux, python 3.5.1-final-0 -----------
Name                                  Stmts   Miss  Cover
---------------------------------------------------------
vcsinfo/__init__.py                       0      0   100%
vcsinfo/exceptions.py                     4      4     0%
vcsinfo/factory.py                        7      4    43%
vcsinfo/implementations/__init__.py       0      0   100%
vcsinfo/implementations/git.py          120     43    64%
---------------------------------------------------------
TOTAL                                   131     51    61%
```

Whereas if I run it directyly with `$ python -m pytest --cov-config=.coveragerc --cov=vcsinfo/ tests` the coverage report reads:

```
----------- coverage: platform linux, python 3.5.1-final-0 -----------
Name                                  Stmts   Miss  Cover
---------------------------------------------------------
vcsinfo/__init__.py                       0      0   100%
vcsinfo/exceptions.py                     4      0   100%
vcsinfo/factory.py                        7      0   100%
vcsinfo/implementations/__init__.py       0      0   100%
vcsinfo/implementations/git.py          120      0   100%
---------------------------------------------------------
TOTAL                                   131      0   100%
```

**Comment by marscher** [comment]
I also observe such behaviour within our project. Decorators, class definitions, properties are shown as never executed (maybe because pytest already imported the modules prior coverage recorded execution?).
I can provide more details if desired.

**Comment by ionelmc** [comment]
@teake, the problem is that you import the code before running pytest. 

Besides making lazy importing (if even possible, I haven't a clue how to make setuptools call some code when it needs the version) you could run pytest in a subprocess (using `sys.executable` or similar to make sure you run same interpreter).

However, there may be another way (this is very similar to measuring coverage when testing pytest plugins) - you could force pytest-cov to load its "engine" by manually setting the COV_CORE_ env vars, an example: https://github.com/ionelmc/pytest-benchmark/blob/master/tox.ini#L23-L25

Interestingly enough, neither does https://github.com/pypa/setuptools_scm have a much different `setup.py` regarding the self-import, however, setuptools_scm don't use `setup.py test` to run tests. It's not necessary anyway, is it?

**Comment by teake** [comment]
Ah, yes, you're right. The culprit was indeed the import of the package under test in setup.py. If I remove that import, the coverage is back to normal.
And indeed it is not necessary to run tests via setup.py. I'll probably switch to tox for my test handling.
