### ISSUE TITLE
flake8 and coverage interaction slows things down unnecessarily

### ISSUE THREAD

**Issue by timj** [pytest-dev/pytest-cov#210]
We are noticing that enabling flake8 and coverage testing with pytest is slowing test execution down by a factor of 4. In one example, the tests run in 7 seconds without either plugin. Adding coverage slows down test execution to 13 seconds. Adding flake8 (no coverage) is 15 seconds, and using both is 30 seconds.

Is there any way that coverage can be disabled for flake8 testing? Or is coverage enabled for everything in the python process (including pytest itself) so it's fundamentally impossible to pick and choose which tests have coverage enabled?

**Comment by blueyed** [comment]
Are you using pytest-flake8?

I suggest using flake8 by itself then - makes it also easier to distinguish styling issues from test failures (especially when run in separate jobs).

**Comment by timj** [comment]
Yes, we are using `pytest-flake8`. Doing that has the advantage that the test suite fails if there is a flake8 failure (which seems to be a good thing from our point of view). I assume the answer to my question is "no, coverage must also run with the flake8 tests".

**Comment by RonnyPfannschmidt** [comment]
i beleive the main reason its not handled is that nobod y fixed it

part of that is that more and more people come to the realization that style checks as extra ci step and editor integration are much better structurally than pretending they are tests

even more so now that we have tools like black that remove them from the set of issues that come up to begin with

**Comment by blueyed** [comment]
@timj 
> Yes, we are using pytest-flake8

That might make you a maintainer then.. ;)

Looking at its source now showed me this: https://github.com/tholo/pytest-flake8/blob/25bbd3b42d3aa0962fb736202115dae9e5d2cd7c/pytest_flake8.py#L108-L117

It appears to call flake8 on every file - which is certainly slower like calling flake8 itself with a list of files.

Therefore I even recommend not using pytest-flake8 even more.
(the main reason still is that a separate lint-job-failure is better than tests-failed-because-of-missing-newline-failure)

**Comment by blueyed** [comment]
Closing this for pytest-cov.
