### ISSUE TITLE
Increase minimum version of coverage to fix minor bug

### ISSUE THREAD

**Issue by sjjessop** [pytest-dev/pytest-cov#421]
The actual bug is described here (I raised an issue against pytest): https://github.com/pytest-dev/pytest/issues/7632

In summary: suppose you have a multi-line assert with a lambda in it. Then, when running as as a test under pytest (but not when running under coverage alone and called from ``__main__``), the lambda is incorrectly reported as "didn't finish", with a partial miss at the line of the assert.

The fix is to upgrade to the latest ``coverage``. So, somewhere between coverage==4.5.4 and coverage==5.2.1 is a version which fixes the issue.

pytest-cov currently requires coverage>=4.4 in setup.py. Is this issue a good enough reason to increase that lower bound? I'm willing to do the binary chop to find out what version is needed, if that will help!

**Comment by The-Compiler** [comment]
FWIW I'm -1 on this, given that the bug doesn't have anything to do with pytest-cov. There are bugs fixed in various coverage.py releases and some of them might affect coverage.py when run under pytest, but I don't think that's a reason for this plugin to force a newer version.

**Comment by The-Compiler** [comment]
I did a quick git bisect of coverage.py out of curiosity, but unfortunately without much success:

```
The merge base 2716d2cb62788e7053b3b73bf200acad52cd2360 is bad.
This means the bug has been fixed between 2716d2cb62788e7053b3b73bf200acad52cd2360 and [7adc519d681f01448bfeec99b9a23a3b8da86eb6].
```

From a quick manual test, coverage-5.0a6 is bad, coverage-5.0a7 is good. Not sure what's up with the coverage.py repo, but git bisect doesn't let me bisect between those two either:

```
Some good revs are not ancestors of the bad rev.
git bisect cannot work properly in this case.
Maybe you mistook good and bad revs?
```

Because my curiosity sometimes knows no bounds, I tracked it down manually, and this commit fixes things: https://github.com/nedbat/coveragepy/commit/341e737bd5010ffd794b029b3051a7ae210bfef2

No idea what's pytest-specific about that, though. I suppose there are some scenarios where the same bug would show outside of pytest as well.

**Comment by sjjessop** [comment]
I'm at most +0.5 on it myself. If it's a stone cold bug in coverage, then I guess pytest-cov is defined to run the coverage you have installed, regardless of how good or bad it is. If it's anything to do with pytest's `assert` magic, though, I was thinking maybe it could turn out to be a feature of coverage that pytest was (perhaps unknowingly) relying on.

**Comment by ionelmc** [comment]
It has to be pretty bad to annoy users with dep constraint changes. I want to avoid complaints that pytest-cov doesn't install unless absolutely necessary (eg: pytest-cov has no support for that specific version of coveragepy).
